/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automat.mp;

import java.awt.event.ActionEvent;

/**
 *
 * @author Angelo Ablaza
 */
public class SolutionFrame extends javax.swing.JFrame {

    /**
     * Creates new form SolutionFrame
     */
    public SolutionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        solutionOneBtn = new javax.swing.JButton();
        solutionTwoBtn = new javax.swing.JButton();
        solutionThreeBtn = new javax.swing.JButton();
        solutionFourBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jPanel2.setLayout(new java.awt.GridBagLayout());

        solutionOneBtn.setBackground(new java.awt.Color(0, 0, 51));
        solutionOneBtn.setForeground(new java.awt.Color(255, 255, 255));
        solutionOneBtn.setText("Solution 1");
        solutionOneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solutionOneBtnActionPerformed(evt);
            }
        });
        jPanel2.add(solutionOneBtn, new java.awt.GridBagConstraints());

        solutionTwoBtn.setBackground(new java.awt.Color(0, 0, 51));
        solutionTwoBtn.setForeground(new java.awt.Color(255, 255, 255));
        solutionTwoBtn.setText("Solution 2");
        solutionTwoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solutionTwoBtnActionPerformed(evt);
            }
        });
        jPanel2.add(solutionTwoBtn, new java.awt.GridBagConstraints());

        solutionThreeBtn.setBackground(new java.awt.Color(0, 0, 51));
        solutionThreeBtn.setForeground(new java.awt.Color(255, 255, 255));
        solutionThreeBtn.setText("Solution 3");
        solutionThreeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solutionThreeBtnActionPerformed(evt);
            }
        });
        jPanel2.add(solutionThreeBtn, new java.awt.GridBagConstraints());

        solutionFourBtn.setBackground(new java.awt.Color(0, 0, 51));
        solutionFourBtn.setForeground(new java.awt.Color(255, 255, 255));
        solutionFourBtn.setText("Solution 4");
        solutionFourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solutionFourBtnActionPerformed(evt);
            }
        });
        jPanel2.add(solutionFourBtn, new java.awt.GridBagConstraints());

        jTextArea1.setBackground(new java.awt.Color(0, 0, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Solution 1\n1. Transport Cow and Lion\n2. Transport Lion\n3. Transport Human 1 and Human 2\n4. Transport Cow\n5. Transport Lion and Grain\n6. Transport Lion\n7. Transport Lion and Cow");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automat/final/Solution1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solutionFourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solutionFourBtnActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automat/final/Solution4.png"))); // NOI18N
        jTextArea1.setText("Solution 4\n" 
                + "1. Transport Cow and Lion\n"
                + "2. Transport Lion\n"
                + "3. Transport Lion and Grain\n"
                + "4. Transport Cow\n"
                + "5. Tansport Human 1 and Human 2\n"
                + "6. Transport Lion\n"
                + "7. Transport Lion and Cow");
    }//GEN-LAST:event_solutionFourBtnActionPerformed

    private void solutionOneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solutionOneBtnActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automat/final/Solution1.png"))); // NOI18N
        jTextArea1.setText("Solution 1\n"
                + "1. Transport Cow and Lion\n"
                + "2. Transport Lion\n"
                + "3. Transport Human 1 and Human 2\n"
                + "4. Transport Cow\n"
                + "5. Transport Lion and Grain\n"
                + "6. Transport Lion\n"
                + "7. Transport Lion and Cow");
    }//GEN-LAST:event_solutionOneBtnActionPerformed

    private void solutionTwoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solutionTwoBtnActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automat/final/Solution2.png"))); // NOI18N
        jTextArea1.setText("Solution 2\n"
                + "1. Transport Cow and Lion\n"
                + "2. Transport Cow\n"
                + "3. Transport Cow and Grain\n"
                + "4. Transport Cow\n"
                + "5. Tansport Human 1 and Human 2\n"
                + "6. Transport Lion\n"
                + "7. Transport Lion and Cow");
    }//GEN-LAST:event_solutionTwoBtnActionPerformed

    private void solutionThreeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solutionThreeBtnActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automat/final/Solution3.png"))); // NOI18N
        jTextArea1.setText("Solution 3\n"
                + "1. Transport Cow and Lion\n"
                + "2. Transport Lion\n"
                + "3. Transport Human 1 and Human 2\n"
                + "4. Transport Cow\n"
                + "5. Tansport Cow and Grain\n"
                + "6. Transport Cow\n"
                + "7. Transport Lion and Cow");
    }//GEN-LAST:event_solutionThreeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SolutionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SolutionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SolutionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SolutionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SolutionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton solutionFourBtn;
    private javax.swing.JButton solutionOneBtn;
    private javax.swing.JButton solutionThreeBtn;
    private javax.swing.JButton solutionTwoBtn;
    // End of variables declaration//GEN-END:variables
}
